namespace OnlineExamSystem.Exam.Application.Exams.Update;

public record UpdateExamCommand(
    Guid ExamId,
    string Title,
    string Description,
    string ExamType,
    int DurationMinutes,
    int TotalMarks,
    int PassingMarks,
    string Instructions,
    bool ShuffleQuestions,
    bool ShuffleOptions,
    bool ShowResult,
    bool ShowCorrectAnswers,
    bool AllowReview,
    DateTime? StartAtUtc,
    DateTime? EndAtUtc,
    int MaxAttempts,
    bool NegativeMarkingEnabled,
    decimal NegativeMarks,
    bool ShowSectionSummaryToStudents,
    bool AllowCalculator,
    bool AllowNotes,
    bool AutoSubmitOnTimeEnd,
    bool ConfirmBeforeSubmit,
    string? ExamCode = null);
