<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineExamSystem.Submission.Application\OnlineExamSystem.Submission.Application.csproj" />
    <ProjectReference Include="..\OnlineExamSystem.Submission.Infrastructure\OnlineExamSystem.Submission.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\OnlineExamSystem.Shared.Contracts\OnlineExamSystem.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
