// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineExamSystem.Exam.Infrastructure.Persistence;

#nullable disable

namespace OnlineExamSystem.Exam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    [Migration("20260822005658_AddExamCode")]
    partial class AddExamCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ExamAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowLateJoin")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowReviewAfterSubmit")
                        .HasColumnType("bit");

                    b.Property<int>("AssignmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentNumber"));

                    b.Property<bool>("AutoSubmitOnTimeOver")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnableLiveVideo")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableProctoring")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GraceTimeMinutes")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("ShowCorrectAnswers")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInstructions")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowResultsAfterSubmit")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentNumber")
                        .IsUnique();

                    b.HasIndex("ExamId");

                    b.ToTable("ExamAssignments");
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ExamAssignmentTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExamAssignmentId", "UserId")
                        .IsUnique();

                    b.ToTable("ExamAssignmentTargets");
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ExamPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowCalculator")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowNotes")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowReview")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoSubmitOnTimeEnd")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ConfirmBeforeSubmit")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainsSections")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ExamType")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("NegativeMarkingEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("NegativeMarks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PassingMarks")
                        .HasColumnType("int");

                    b.Property<bool>("ShowCorrectAnswers")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowResult")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowSectionSummaryToStudents")
                        .HasColumnType("bit");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalMarks")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ExamReminderLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Window")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "UserId", "Window")
                        .IsUnique();

                    b.ToTable("ExamReminderLogs");
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ProctoringSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CopyPasteBlockingEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FaceDetectionEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("FullscreenExitEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MultiPersonDetectionEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleMonitorsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleTabsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("ProctoringEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("RightClickBlockingEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("ScreenMonitoringEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProctoringSettings");
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ReminderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enable1HourReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("Enable24HourReminder")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ReminderSettings");
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowReview")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Marks")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NavigationType")
                        .HasColumnType("int");

                    b.Property<bool>("NegativeMarkingEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("NegativeMarks")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ExamAssignment", b =>
                {
                    b.HasOne("OnlineExamSystem.Exam.Domain.Entities.ExamPaper", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ExamAssignmentTarget", b =>
                {
                    b.HasOne("OnlineExamSystem.Exam.Domain.Entities.ExamAssignment", null)
                        .WithMany()
                        .HasForeignKey("ExamAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.ExamReminderLog", b =>
                {
                    b.HasOne("OnlineExamSystem.Exam.Domain.Entities.ExamAssignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineExamSystem.Exam.Domain.Entities.Section", b =>
                {
                    b.HasOne("OnlineExamSystem.Exam.Domain.Entities.ExamPaper", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
