namespace OnlineExamSystem.Shared.Contracts.Requests.Exam;

public record UpdateExamRequest(
    string Title,
    string Description,
    string CreationMethod,
    int DurationMinutes,
    int TotalMarks,
    int PassingMarks,
    string Instructions,
    bool ShuffleQuestions,
    bool ShuffleOptions,
    bool ShowResult,
    bool ShowCorrectAnswers,
    bool AllowReview,
    DateTime? StartAtUtc,
    DateTime? EndAtUtc,
    int MaxAttempts,
    bool NegativeMarkingEnabled,
    decimal NegativeMarks,
    bool ShowSectionSummaryToStudents,
    bool AllowCalculator,
    bool AllowNotes,
    bool AutoSubmitOnTimeEnd,
    bool ConfirmBeforeSubmit,
    string? ExamCode = null,
    Guid? ExamTypeId = null,
    Dictionary<string, string>? AcademicFields = null,
    bool CertificateEnabled = false,
    int MinimumCertificateScorePercent = 80);
